[package]
name = "google-cloudevents"
description = "Prost codegen structs for Google CloudEvent types"
license = "MIT"
version = "0.1.3"
edition = "2021"

[dependencies]
prost = "0.13.4"
prost-types = "0.13.4"

