// This file is @generated by prost-build.
/// A BeyondCorp AppGateway resource represents a BeyondCorp protected AppGateway
/// to a remote application. It creates all the necessary GCP components needed
/// for creating a BeyondCorp protected AppGateway. Multiple connectors can be
/// authorised for a single AppGateway.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppGateway {
    /// Required. Unique resource name of the AppGateway.
    /// The name is ignored when creating an AppGateway.
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Output only. Timestamp when the resource was created.
    #[prost(message, optional, tag = "2")]
    pub create_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Output only. Timestamp when the resource was last modified.
    #[prost(message, optional, tag = "3")]
    pub update_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional. Resource labels to represent user provided metadata.
    #[prost(map = "string, string", tag = "4")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Optional. An arbitrary user-provided name for the AppGateway. Cannot exceed
    /// 64 characters.
    #[prost(string, tag = "5")]
    pub display_name: ::prost::alloc::string::String,
    /// Output only. A unique identifier for the instance generated by the
    /// system.
    #[prost(string, tag = "6")]
    pub uid: ::prost::alloc::string::String,
    /// Required. The type of network connectivity used by the AppGateway.
    #[prost(enumeration = "app_gateway::Type", tag = "7")]
    pub r#type: i32,
    /// Output only. The current state of the AppGateway.
    #[prost(enumeration = "app_gateway::State", tag = "8")]
    pub state: i32,
    /// Output only. Server-defined URI for this resource.
    #[prost(string, tag = "9")]
    pub uri: ::prost::alloc::string::String,
    /// Output only. A list of connections allocated for the Gateway
    #[prost(message, repeated, tag = "10")]
    pub allocated_connections: ::prost::alloc::vec::Vec<
        app_gateway::AllocatedConnection,
    >,
    /// Required. The type of hosting used by the AppGateway.
    #[prost(enumeration = "app_gateway::HostType", tag = "11")]
    pub host_type: i32,
}
/// Nested message and enum types in `AppGateway`.
pub mod app_gateway {
    /// Allocated connection of the AppGateway.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AllocatedConnection {
        /// Required. The PSC uri of an allocated connection
        #[prost(string, tag = "1")]
        pub psc_uri: ::prost::alloc::string::String,
        /// Required. The ingress port of an allocated connection
        #[prost(int32, tag = "2")]
        pub ingress_port: i32,
    }
    /// Enum containing list of all possible network connectivity options
    /// supported by BeyondCorp AppGateway.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        /// Default value. This value is unused.
        Unspecified = 0,
        /// TCP Proxy based BeyondCorp Connection. API will default to this if unset.
        TcpProxy = 1,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "TYPE_UNSPECIFIED",
                Self::TcpProxy => "TCP_PROXY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "TCP_PROXY" => Some(Self::TcpProxy),
                _ => None,
            }
        }
    }
    /// Represents the different states of an AppGateway.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum State {
        /// Default value. This value is unused.
        Unspecified = 0,
        /// AppGateway is being created.
        Creating = 1,
        /// AppGateway has been created.
        Created = 2,
        /// AppGateway's configuration is being updated.
        Updating = 3,
        /// AppGateway is being deleted.
        Deleting = 4,
        /// AppGateway is down and may be restored in the future.
        /// This happens when CCFE sends ProjectState = OFF.
        Down = 5,
    }
    impl State {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "STATE_UNSPECIFIED",
                Self::Creating => "CREATING",
                Self::Created => "CREATED",
                Self::Updating => "UPDATING",
                Self::Deleting => "DELETING",
                Self::Down => "DOWN",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STATE_UNSPECIFIED" => Some(Self::Unspecified),
                "CREATING" => Some(Self::Creating),
                "CREATED" => Some(Self::Created),
                "UPDATING" => Some(Self::Updating),
                "DELETING" => Some(Self::Deleting),
                "DOWN" => Some(Self::Down),
                _ => None,
            }
        }
    }
    /// Enum containing list of all possible host types supported by BeyondCorp
    /// Connection.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum HostType {
        /// Default value. This value is unused.
        Unspecified = 0,
        /// AppGateway hosted in a GCP regional managed instance group.
        GcpRegionalMig = 1,
    }
    impl HostType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "HOST_TYPE_UNSPECIFIED",
                Self::GcpRegionalMig => "GCP_REGIONAL_MIG",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HOST_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "GCP_REGIONAL_MIG" => Some(Self::GcpRegionalMig),
                _ => None,
            }
        }
    }
}
/// The data within all AppGateway events.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppGatewayEventData {
    /// Optional. The AppGateway event payload. Unset for deletion events.
    #[prost(message, optional, tag = "1")]
    pub payload: ::core::option::Option<AppGateway>,
}
/// The CloudEvent raised when an AppGateway is created.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppGatewayCreatedEvent {
    /// The data associated with the event.
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<AppGatewayEventData>,
}
/// The CloudEvent raised when an AppGateway is deleted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppGatewayDeletedEvent {
    /// The data associated with the event.
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<AppGatewayEventData>,
}
